replicaCount: 2

image:
  repository: your-dockerhub-username/drupal-app
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: drupal-dev.your-domain.com   # Change the subdomain for each environment
      paths:
        - /
