name: Build and Deploy Drupal

on:
  push:
    branches:
      - dev
      - stage
      - qa
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/drupal-app:${{ github.ref }} .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push your-dockerhub-username/drupal-app:${{ github.ref }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, stage, qa, prod]

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Helm Upgrade
        run: |
          helm upgrade drupal-${{ matrix.environment }} ./helm-chart \
            -f helm-chart/values-${{ matrix.environment }}.yaml
